workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        # iOS configuration
        BUNDLE_ID: "com.oryxinvestmentsegypt.oryx"
        # GitHub integration (optional)
        GITHUB_TOKEN: Encrypted(...) # Your GitHub personal access token
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.oryxinvestmentsegypt.oryx
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build iOS
        script: |
          # Build iOS release without code signing
          flutter build ios \
            --release \
            --no-codesign \
            --build-name="1.0.0" \
            --build-number="13"
      - name: Code signing
        script: |
          # Set up code signing
          keychain initialize
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build IPA
        script: |
          # Build IPA with code signing
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath build/ios/archive/Runner.xcarchive \
            archive | xcodebuild
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - gtes987@gmail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - group name 1
          - group name 2
