class Autogenerated {
  String? message;
  Data? data;

  Autogenerated({this.message, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    data = json['data'] != null ? Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['message'] = message;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class Data {
  int? id;
  String? name;
  int? categoryId;
  String? category;
  String? categoryImage;
  int? propertyTypeId;
  String? propertyType;
  int? price;
  String? priceFormat;
  int? furnishedType;
  int? sallerType;
  int? propertyFor;
  int? ageOfProperty;
  int? maintenance;
  int? securityDeposit;
  int? brokerage;
  int? bhk;
  String? sqft;
  String? description;
  String? country;
  String? state;
  String? city;
  String? latitude;
  String? longitude;
  String? address;
  String? videoUrl;
  int? status;
  int? premiumProperty;
  String? propertyImage;
  List<String>? propertyGallary;
  List<PropertyGallaryArray>? propertyGallaryArray;
  String? createdAt;
  String? updatedAt;
  int? isFavourite;
  int? advertisementProperty;
  String? advertisementPropertyDate;

  Data(
      {this.id,
        this.name,
        this.categoryId,
        this.category,
        this.categoryImage,
        this.propertyTypeId,
        this.propertyType,
        this.price,
        this.priceFormat,
        this.furnishedType,
        this.sallerType,
        this.propertyFor,
        this.ageOfProperty,
        this.maintenance,
        this.securityDeposit,
        this.brokerage,
        this.bhk,
        this.sqft,
        this.description,
        this.country,
        this.state,
        this.city,
        this.latitude,
        this.longitude,
        this.address,
        this.videoUrl,
        this.status,
        this.premiumProperty,
        this.propertyImage,
        this.propertyGallary,
        this.propertyGallaryArray,
        this.createdAt,
        this.updatedAt,
        this.isFavourite,
        this.advertisementProperty,
        this.advertisementPropertyDate});

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    categoryId = json['category_id'];
    category = json['category'];
    categoryImage = json['category_image'];
    propertyTypeId = json['property_type_id'];
    propertyType = json['property_type'];
    price = json['price'];
    priceFormat = json['price_format'];
    furnishedType = json['furnished_type'];
    sallerType = json['saller_type'];
    propertyFor = json['property_for'];
    ageOfProperty = json['age_of_property'];
    maintenance = json['maintenance'];
    securityDeposit = json['security_deposit'];
    brokerage = json['brokerage'];
    bhk = json['bhk'];
    sqft = json['sqft'];
    description = json['description'];
    country = json['country'];
    state = json['state'];
    city = json['city'];
    latitude = json['latitude'];
    longitude = json['longitude'];
    address = json['address'];
    videoUrl = json['video_url'];
    status = json['status'];
    premiumProperty = json['premium_property'];
    propertyImage = json['property_image'];
    propertyGallary = json['property_gallary'].cast<String>();
    if (json['property_gallary_array'] != null) {
      propertyGallaryArray = <PropertyGallaryArray>[];
      json['property_gallary_array'].forEach((v) {
        propertyGallaryArray!.add(PropertyGallaryArray.fromJson(v));
      });
    }
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    isFavourite = json['is_favourite'];
    advertisementProperty = json['advertisement_property'];
    advertisementPropertyDate = json['advertisement_property_date'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['category_id'] = categoryId;
    data['category'] = category;
    data['category_image'] = categoryImage;
    data['property_type_id'] = propertyTypeId;
    data['property_type'] = propertyType;
    data['price'] = price;
    data['price_format'] = priceFormat;
    data['furnished_type'] = furnishedType;
    data['saller_type'] = sallerType;
    data['property_for'] = propertyFor;
    data['age_of_property'] = ageOfProperty;
    data['maintenance'] = maintenance;
    data['security_deposit'] = securityDeposit;
    data['brokerage'] = brokerage;
    data['bhk'] = bhk;
    data['sqft'] = sqft;
    data['description'] = description;
    data['country'] = country;
    data['state'] = state;
    data['city'] = city;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    data['address'] = address;
    data['video_url'] = videoUrl;
    data['status'] = status;
    data['premium_property'] = premiumProperty;
    data['property_image'] = propertyImage;
    data['property_gallary'] = propertyGallary;
    if (propertyGallaryArray != null) {
      data['property_gallary_array'] =
          propertyGallaryArray!.map((v) => v.toJson()).toList();
    }
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['is_favourite'] = isFavourite;
    data['advertisement_property'] = advertisementProperty;
    data['advertisement_property_date'] = advertisementPropertyDate;
    return data;
  }
}

class PropertyGallaryArray {
  int? id;
  String? url;

  PropertyGallaryArray({this.id, this.url});

  PropertyGallaryArray.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    url = json['url'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['url'] = url;
    return data;
  }
}
